---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: free5gc
resources:
  - upf-0x01010203-sa.yaml
  - upf-0x01010203-rbac.yaml
  - upf-0x01010203-service.yaml
  - upf-0x01010203-deployment.yaml

# declare ConfigMap from a ConfigMapGenerator
configMapGenerator:
- name: free5gc-upf-0x01010203-config
  namespace: free5gc
  files:
    - upfcfg.yaml=config/upfcfg-0x01010203.yaml
