---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: free5gc
resources:
  - ueransim-ue-sa.yaml
  - ueransim-ue-rbac.yaml
  # - ueransim-ue-service.yaml
  - ueransim-ue-deployment.yaml

# declare ConfigMap from a ConfigMapGenerator
configMapGenerator:
- name: free5gc-ueransim-ue-0x01010203-config
  namespace: free5gc
  files:
    - config/free5gc-ue.yaml
